<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IT</name>
   <tag></tag>
   <elementGuidId>e6c22fd2-32ee-440d-9635-54a1bfe9971d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.BreadcrumbsSmall_breadcrumb_item__cstfm.undefined > a.BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87f55f88-07be-4dc7-9964-4e6f81137132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      <webElementGuid>00c7cd49-7606-42a9-b2c4-f9c1d9a319fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1</value>
      <webElementGuid>980128dd-4ae7-4caa-9129-87c29fb9b5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IT・通信</value>
      <webElementGuid>50593f68-caf2-4722-bee0-5a5520b58a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/nav[@class=&quot;&quot;]/ul[@class=&quot;BreadcrumbsSmall_breadcrumb_list__Ifq8c&quot;]/li[@class=&quot;BreadcrumbsSmall_breadcrumb_item__cstfm undefined&quot;]/a[@class=&quot;BreadcrumbsSmall_breadcrumb_link__NM8Gy&quot;]</value>
      <webElementGuid>ae801827-d46c-4308-a749-15aa8fbca937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/nav/ul/li[2]/a</value>
      <webElementGuid>a1571f6c-9bad-4c21-8862-532490dfa0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IT・通信')]</value>
      <webElementGuid>1ce2f6a5-c93f-4200-983a-5e11c1ec5527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ホーム'])[1]/following::a[1]</value>
      <webElementGuid>115797cd-16e1-46e2-a1a3-f1c3ba7d879a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='絞り込む'])[1]/following::a[2]</value>
      <webElementGuid>4fec8874-8150-47d2-844a-ebbbc6af7092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IT・通信']/parent::*</value>
      <webElementGuid>094a0e93-b217-4d9c-8458-805a0d374704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1')]</value>
      <webElementGuid>f4e39ab2-2a8b-4c83-8386-7b7d3305129c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>6d2d4929-00d6-4fd4-8a4a-08ab7e474a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1' and (text() = 'IT・通信' or . = 'IT・通信')]</value>
      <webElementGuid>589385f6-e9dc-4446-bea3-541181387c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
