<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_occupation_dropdown</name>
   <tag></tag>
   <elementGuidId>7f014494-0535-4ca5-a393-320c0f30c46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/div[2]/div/div/form/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f8c208b-2123-4b54-8bdc-47f93ae87352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RefineForm_occupation_title__aZNVm</value>
      <webElementGuid>74dc7a5d-a3c5-4bbc-b4bb-c996b914d9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>職種選択</value>
      <webElementGuid>860dfb57-e03b-4757-8d36-0a410154e948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]/div[@class=&quot;Search_refine_form_pc__aNEXB&quot;]/div[1]/form[@class=&quot;RefineForm_side_form__2IUw1&quot;]/div[@class=&quot;RefineForm_side_item__tcBpT&quot;]/div[@class=&quot;RefineForm_occupation_section__p7sGu&quot;]/div[@class=&quot;RefineForm_occupation_title__aZNVm&quot;]</value>
      <webElementGuid>68504910-ea65-4564-a93a-baa2ea9f659e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/div[2]/div/div/form/div[4]/div/div</value>
      <webElementGuid>7c687a27-7529-4e7a-a69d-a59500e3b4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='フレックスタイム制'])[2]/following::div[3]</value>
      <webElementGuid>7c89a2c4-df59-48bc-9931-481f699e4d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='リモートワーク／在宅勤務／内職'])[2]/following::div[5]</value>
      <webElementGuid>a72f9a3d-32f1-460e-b060-4aeeb937abc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div[4]/div/div</value>
      <webElementGuid>2603bef7-3a29-46b4-a194-8aa187ed547b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '職種選択' or . = '職種選択')]</value>
      <webElementGuid>045704c6-ee19-479a-991e-493e44dd3660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
