<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sub-side-freeword-text</name>
   <tag></tag>
   <elementGuidId>30989ce6-6ecc-4b15-a548-00db87d620dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c97a4de-d7e8-4cac-8f27-9692f9aa67e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23246272-c1ab-4197-b366-19c12e32f232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-side-freeword-text</value>
      <webElementGuid>e7334218-8486-4ebb-bf8e-0f20229228ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>89276160-5982-461f-a6f1-8ae1b2b6e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RefineForm_side_freeword_text__60MVP</value>
      <webElementGuid>415e4c89-226a-4e5e-9755-843cdfff9931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>9e82dcad-c5ff-44f4-a9c2-50c9e255cd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0117b7c-f96c-4f55-af8b-832544b7034f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>abc</value>
      <webElementGuid>84a79c3e-1c53-4677-b9ef-01627daef624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]/div[@class=&quot;Search_refine_form_pc__aNEXB&quot;]/div[1]/form[@class=&quot;RefineForm_side_form__2IUw1&quot;]/div[@class=&quot;RefineForm_side_item__tcBpT&quot;]/div[@class=&quot;AccordionMenu_element__nRtPE AccordionMenu_blue-no-border__YqVad  AccordionMenu_is_open__9Vt_Q&quot;]/div[@id=&quot;list-pull-down-menu-1&quot;]/div[@class=&quot;AccordionMenu_children__7JEuS&quot;]/div[1]/div[@class=&quot;RefineForm_side_freeword_wrap__kbobI&quot;]/input[@id=&quot;sub-side-freeword-text&quot;]</value>
      <webElementGuid>dc3d8836-71b4-4b20-89f8-dc0aa5254ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      <webElementGuid>2bb3f30f-f197-4423-bddb-153825e6e721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='list-pull-down-menu-1']/div/div/div/input)[3]</value>
      <webElementGuid>feac2b42-0cd9-49a0-a273-11bc2585a504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>4752f8d1-ee22-4896-b845-44a008654053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub-side-freeword-text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>d6ad62f7-59e5-49d5-a15e-819bb88081f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
