<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_occupation_industry_freeword</name>
   <tag></tag>
   <elementGuidId>5c499604-d9e4-49e9-935a-dc3367285284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='abc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0def660-6988-4e79-aa2c-ef0df0723a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ccd49d4-0c54-43ef-8a1d-647bc4061cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>619cb131-92eb-40ce-a08b-163b724e6944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>fe3101cc-7286-498d-89d8-02cacf820270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>abc</value>
      <webElementGuid>d0fc7100-10de-4195-b214-3d112dc65780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv&quot;]/div[@class=&quot;Header_header_left__xW1Ah&quot;]/form[@class=&quot;Header_search_wrapper__xLSOA&quot;]/div[@class=&quot;Header_search_form_free_word__nPO9u&quot;]/div[@class=&quot;SearchInput_base_input__Fe0O_ SearchInput_small___xUhf&quot;]/div[1]/input[1]</value>
      <webElementGuid>d79455cb-e55e-4168-b568-ec68f3f672ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='abc']</value>
      <webElementGuid>04c84d65-2ab6-4892-898e-0789a2ff1d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div/form/div/div/div/input</value>
      <webElementGuid>75d8261c-20d7-4be7-be7a-d48a3c798653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c7b57c0e-0d61-45b8-8f81-41c3e330f87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>bfb8f63d-68bf-47d9-a50e-b7c1a16ea807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
