<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prefecture_city_station</name>
   <tag></tag>
   <elementGuidId>1c0b7f7b-598a-44fd-b9e7-dcc0c3500c57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97c81dc4-8946-4b67-91bb-4749ce985f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>658a494e-d661-4881-bfb4-a5195719e3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>630dec82-8bf4-403e-8006-352e9d0e7522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>都道府県、市区群、駅名など</value>
      <webElementGuid>72e47ece-62dd-47de-93a2-5e8810a082f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv&quot;]/div[@class=&quot;Header_header_left__xW1Ah&quot;]/form[@class=&quot;Header_search_wrapper__xLSOA&quot;]/div[@class=&quot;Header_search_form_free_word__nPO9u&quot;]/div[@class=&quot;SearchInput_base_input__Fe0O_ SearchInput_small___xUhf&quot;]/div[1]/input[1]</value>
      <webElementGuid>ab6bf9ec-f2ea-431a-ba29-4554a7cd3542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>fd485dc5-8ac3-47ed-a8e9-278a6b98d391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>037c69a3-6351-4edf-bb67-6a08c5f0d90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c115c607-629c-4ca2-a508-1198208c9efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '都道府県、市区群、駅名など']</value>
      <webElementGuid>0e7e5369-c416-4cbb-8f9a-9006e65d29b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
