<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_abc</name>
   <tag></tag>
   <elementGuidId>7af288dd-af05-47cf-9ce0-b2bba5704e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/div/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Search_search_word__82rCx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e8b91b3-e604-4b64-8da0-96d7877a64d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Search_search_word__82rCx</value>
      <webElementGuid>d78103f7-d624-400a-aa0d-0049df065bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>abc </value>
      <webElementGuid>ee684c86-72ec-45ad-9f8b-23cf990d8409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_main__5VwLF undefined&quot;]/h1[@class=&quot;Search_search_text__w2ad3&quot;]/span[@class=&quot;Search_search_word__82rCx&quot;]</value>
      <webElementGuid>0f8fc4d2-6501-4667-aecb-44e202f859ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/div/h1/span</value>
      <webElementGuid>39b7f380-cf8e-4f02-bf60-eaf25b81034a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連順'])[1]/preceding::span[3]</value>
      <webElementGuid>c4be3150-734c-4ecc-aa69-f2c369911e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='＃ 大量募集'])[1]/preceding::span[3]</value>
      <webElementGuid>2aeedc29-278a-4bb2-addc-42606e944f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='abc']/parent::*</value>
      <webElementGuid>6a109f60-7ec0-41b0-aec7-998da18c6774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>9b481a07-5e26-48a3-8656-84bd8c6ba80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'abc ' or . = 'abc ')]</value>
      <webElementGuid>764ce332-dc68-464f-8be3-c9962ac0492f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
