<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK2431OK</name>
   <tag></tag>
   <elementGuidId>52fe1191-edb5-4b48-9427-df7b61252739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Search_column_side__TdR2j.Search_archive_side__Bawh1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fac3f565-bc5b-4846-bb78-ae8251edfc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Search_column_side__TdR2j Search_archive_side__Bawh1</value>
      <webElementGuid>643d2029-1a10-4808-b9ab-232f3aa5be68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>フリーワードを含まない地域働き方・雇用形態正社員アルバイト・パート契約社員派遣社員業務委託未経験者歓迎新卒OK副業・Ｗワークリモートワーク／在宅勤務／内職フレックスタイム制職種選択業種選択給与すべて年収時給日給下限なし〜上限なし求人掲載日24時間以内3日以内1週間以内こだわり条件フリーター歓迎学歴不問社会保険完備短期・期間限定社員登用あり交通費支給制服貸与バイク・車通勤OK第二新卒歓迎服装自由条件を保存する解除絞り込む条件变更</value>
      <webElementGuid>2a6b4f31-dbfb-40fd-866d-8d23ea599661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]</value>
      <webElementGuid>4bd60a7b-82f5-451f-969a-72c6a6c4346e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/div[2]</value>
      <webElementGuid>af7d5113-89b8-4d34-87e3-e02b7961b0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連順'])[1]/following::div[5]</value>
      <webElementGuid>f5b94628-93f8-4a65-9611-fddd03ecec39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]</value>
      <webElementGuid>2229c36c-86c3-4044-850f-95d9f3bdf287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'フリーワードを含まない地域働き方・雇用形態正社員アルバイト・パート契約社員派遣社員業務委託未経験者歓迎新卒OK副業・Ｗワークリモートワーク／在宅勤務／内職フレックスタイム制職種選択業種選択給与すべて年収時給日給下限なし〜上限なし求人掲載日24時間以内3日以内1週間以内こだわり条件フリーター歓迎学歴不問社会保険完備短期・期間限定社員登用あり交通費支給制服貸与バイク・車通勤OK第二新卒歓迎服装自由条件を保存する解除絞り込む条件变更' or . = 'フリーワードを含まない地域働き方・雇用形態正社員アルバイト・パート契約社員派遣社員業務委託未経験者歓迎新卒OK副業・Ｗワークリモートワーク／在宅勤務／内職フレックスタイム制職種選択業種選択給与すべて年収時給日給下限なし〜上限なし求人掲載日24時間以内3日以内1週間以内こだわり条件フリーター歓迎学歴不問社会保険完備短期・期間限定社員登用あり交通費支給制服貸与バイク・車通勤OK第二新卒歓迎服装自由条件を保存する解除絞り込む条件变更')]</value>
      <webElementGuid>ae79a1fd-3af0-438a-99a3-d13d3399b7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
