<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sub-side-freeword-text</name>
   <tag></tag>
   <elementGuidId>98eab1fb-66fb-47d3-b5e1-2cf8ed0ef9dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e1758ac-fe08-4c7e-9ce5-cdd2ccfcae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da92228f-26c8-4218-ab10-9d0b2fa94504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-side-freeword-text</value>
      <webElementGuid>382d3af7-a1aa-4b7d-86f0-0dde36bba02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>2b61361d-150c-44a0-87e3-af45e6b8a306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RefineForm_side_freeword_text__60MVP</value>
      <webElementGuid>b118f938-3688-45a2-a94d-ac08e9edc981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>ec94dd93-abe5-4caa-8c8b-10a35b02d77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dddfceaa-d254-4db2-998b-a4bf373e4803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>abcd</value>
      <webElementGuid>9ffea187-b1b5-4a79-9a7e-e3c9162c9b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]/div[@class=&quot;Search_refine_form_pc__aNEXB&quot;]/div[1]/form[@class=&quot;RefineForm_side_form__2IUw1&quot;]/div[@class=&quot;RefineForm_side_item__tcBpT&quot;]/div[@class=&quot;AccordionMenu_element__nRtPE AccordionMenu_blue-no-border__YqVad  AccordionMenu_is_open__9Vt_Q&quot;]/div[@id=&quot;list-pull-down-menu-1&quot;]/div[@class=&quot;AccordionMenu_children__7JEuS&quot;]/div[1]/div[@class=&quot;RefineForm_side_freeword_wrap__kbobI&quot;]/input[@id=&quot;sub-side-freeword-text&quot;]</value>
      <webElementGuid>3e00ef2d-8a5e-4f66-b1ae-698432e0dd46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      <webElementGuid>a2b29f2e-a934-4a10-b7af-7affc3a467fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='list-pull-down-menu-1']/div/div/div/input)[3]</value>
      <webElementGuid>2aff6a57-6d56-4fb3-9345-e36e69d2480e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>ee05371d-7f81-42d3-b206-22e41fbfd09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub-side-freeword-text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>e36e3659-44fa-4409-9a26-e158796b97e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
