<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>a97a540d-7798-4c2a-8f2a-01aac3572de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='abcd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1abbddc-d807-4b4e-9f80-0fa407d41ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7f54c12-f837-45bf-8e7f-45bd8a79cf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>f50fe761-ac52-478f-863b-9f50e7c92a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>2725956a-88aa-4073-a705-21223cb2ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>abcd</value>
      <webElementGuid>52ebd0ef-9048-41d0-b16b-0423b97d4412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv&quot;]/div[@class=&quot;Header_header_left__xW1Ah&quot;]/form[@class=&quot;Header_search_wrapper__xLSOA&quot;]/div[@class=&quot;Header_search_form_free_word__nPO9u&quot;]/div[@class=&quot;SearchInput_base_input__Fe0O_ SearchInput_small___xUhf&quot;]/div[1]/input[1]</value>
      <webElementGuid>578fb5fb-ec2b-4191-b164-4fc06debdc28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='abcd']</value>
      <webElementGuid>2bc3c65f-293e-492d-b288-e74386a45f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div/form/div/div/div/input</value>
      <webElementGuid>3e442c87-e157-4fa2-b0ba-42651c13ff9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>28aa6250-00b1-4b0e-ab42-575f9930dcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>38cdbcbb-4ab7-4f46-a540-49879aaa4e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
