<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>5b4fc804-c7c6-47ff-b081-74017aeb1efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45a97a43-1e5a-448e-9fec-385cf518114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      <webElementGuid>dbca6f3c-c1f8-47a4-9a74-64bfceeb204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/city%E9%BB%92%E9%83%A8%E5%B8%82</value>
      <webElementGuid>2a9c412f-5cde-4ae5-942f-ecb5c53b0324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>黒部市</value>
      <webElementGuid>eada0bb5-10e9-4d36-bf52-7dfa3fafffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/nav[@class=&quot;&quot;]/ul[@class=&quot;BreadcrumbsSmall_breadcrumb_list__Ifq8c&quot;]/li[@class=&quot;BreadcrumbsSmall_breadcrumb_item__cstfm&quot;]/a[@class=&quot;BreadcrumbsSmall_breadcrumb_link__NM8Gy&quot;]</value>
      <webElementGuid>5f02d6da-eb9c-4433-9c8b-11d17f5222e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/nav/ul/li[2]/a</value>
      <webElementGuid>9963e0d3-e04b-477f-a126-70399efb25b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'黒部市')]</value>
      <webElementGuid>5bf46070-b654-48c8-8d3f-40593ee97310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ホーム'])[1]/following::a[1]</value>
      <webElementGuid>eb99ed61-4634-42d1-8e59-89d53f965fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='絞り込む'])[1]/following::a[2]</value>
      <webElementGuid>380f5c65-add1-4aa7-b0d2-a71d541fa3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新黒部駅'])[1]/preceding::a[1]</value>
      <webElementGuid>52021f87-7629-42f4-91f6-fb313ce35495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='黒部市']/parent::*</value>
      <webElementGuid>b1f4b1c3-1239-4c04-85ee-cabf83feb102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/city%E9%BB%92%E9%83%A8%E5%B8%82')]</value>
      <webElementGuid>288073fb-fcee-4bd9-bce5-fdb9df3fadb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>980dcd39-7975-4437-b555-a750701d71a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/city%E9%BB%92%E9%83%A8%E5%B8%82' and (text() = '黒部市' or . = '黒部市')]</value>
      <webElementGuid>162c8255-c5e3-4687-9f8c-214d2e9839a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
