<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>03e791b4-8142-458f-9054-3a6ed4772f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.BreadcrumbsSmall_breadcrumb_item__cstfm.undefined > a.BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82ec04ab-789f-4a85-b2ea-7fa6d218f402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      <webElementGuid>0bbb8a49-1c81-4108-8403-6cf767b6b607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/city%E9%BB%92%E9%83%A8%E5%B8%82/station%E6%96%B0%E9%BB%92%E9%83%A8%E9%A7%85</value>
      <webElementGuid>cc6f1e7f-517e-4172-ac10-ff57f3c56d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新黒部駅</value>
      <webElementGuid>1c09f074-c74f-4f25-92b8-d19e6e06d099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/nav[@class=&quot;&quot;]/ul[@class=&quot;BreadcrumbsSmall_breadcrumb_list__Ifq8c&quot;]/li[@class=&quot;BreadcrumbsSmall_breadcrumb_item__cstfm undefined&quot;]/a[@class=&quot;BreadcrumbsSmall_breadcrumb_link__NM8Gy&quot;]</value>
      <webElementGuid>a144e3ab-07b0-4454-88d8-a1dca0a6f70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/nav/ul/li[3]/a</value>
      <webElementGuid>3e6c796c-ca36-4110-8c7f-993468371d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'新黒部駅')]</value>
      <webElementGuid>ea1fd1a1-e604-4af7-8a7d-c5b0ac3efdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='黒部市'])[1]/following::a[1]</value>
      <webElementGuid>f79e880a-a964-4bab-957f-3189dd436643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ホーム'])[1]/following::a[2]</value>
      <webElementGuid>318640b8-2721-4944-a7bf-23b61c9bec03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='新黒部駅']/parent::*</value>
      <webElementGuid>e2330aa8-45d8-4af2-a420-4f7e63a91967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/city%E9%BB%92%E9%83%A8%E5%B8%82/station%E6%96%B0%E9%BB%92%E9%83%A8%E9%A7%85')]</value>
      <webElementGuid>e05729d1-586d-4aa5-8894-265eb75aefb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>ed2cd614-d5a1-4b0a-b81b-8ebf09ddbfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/city%E9%BB%92%E9%83%A8%E5%B8%82/station%E6%96%B0%E9%BB%92%E9%83%A8%E9%A7%85' and (text() = '新黒部駅' or . = '新黒部駅')]</value>
      <webElementGuid>18f9dd41-302d-4266-b41a-573f71ca38c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
