<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>b7ca78d7-1184-42d5-8458-529a5dcf66fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.BreadcrumbsSmall_breadcrumb_item__cstfm.undefined > a.BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e974c408-b630-47f2-93da-16b9993d3e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BreadcrumbsSmall_breadcrumb_link__NM8Gy</value>
      <webElementGuid>456442f9-ed34-4217-9025-1f553e375bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/prefecture%E5%8C%97%E6%B5%B7%E9%81%93/city%E6%9C%AD%E5%B9%8C%E5%B8%82</value>
      <webElementGuid>1ca9d9d9-39f6-4c5e-a2b7-2e63eacbcb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>札幌市</value>
      <webElementGuid>ea6c8bcb-f7d9-4449-925a-b808c6f5d6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/nav[@class=&quot;&quot;]/ul[@class=&quot;BreadcrumbsSmall_breadcrumb_list__Ifq8c&quot;]/li[@class=&quot;BreadcrumbsSmall_breadcrumb_item__cstfm undefined&quot;]/a[@class=&quot;BreadcrumbsSmall_breadcrumb_link__NM8Gy&quot;]</value>
      <webElementGuid>8d377b3b-aa6d-46c5-bc7e-cec4c4383a96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/nav/ul/li[3]/a</value>
      <webElementGuid>ad5cedf0-6a56-4318-bc01-6f936cdadbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'札幌市')]</value>
      <webElementGuid>a461809f-b27a-43b2-ad4f-02e78421f750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='北海道'])[1]/following::a[1]</value>
      <webElementGuid>8fb9a833-4f88-4241-b4f7-2067dbdde20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ホーム'])[1]/following::a[2]</value>
      <webElementGuid>412a4650-8424-4555-817d-a794fcfa7b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='札幌市']/parent::*</value>
      <webElementGuid>1363ea3f-03e1-4384-b620-4f5c869565a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/prefecture%E5%8C%97%E6%B5%B7%E9%81%93/city%E6%9C%AD%E5%B9%8C%E5%B8%82')]</value>
      <webElementGuid>92a020e8-5be2-42ec-a53e-61b565f43976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>5fa568b4-ef8b-4f64-8679-7f4ca076de9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/prefecture%E5%8C%97%E6%B5%B7%E9%81%93/city%E6%9C%AD%E5%B9%8C%E5%B8%82' and (text() = '札幌市' or . = '札幌市')]</value>
      <webElementGuid>35d7c4d4-6ce3-4041-b862-9357d561f5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
