<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IT</name>
   <tag></tag>
   <elementGuidId>aa0958b2-b1b6-4a5a-9d20-ce7991b581ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[6]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f781d17f-d08b-41b3-937c-4fa220e12974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Anchor_element__tZBvd Anchor_white_border_gray__yLHOv </value>
      <webElementGuid>89f389fd-ae21-40fa-897c-2472d3608daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1</value>
      <webElementGuid>2dbe527c-d394-4fce-9e86-d4480aa0b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value># IT・通信</value>
      <webElementGuid>aee38f52-3050-4be1-af6c-290a1361c90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_industry__Oh_KK&quot;]/div[@class=&quot;SearchRecruit_type_list_wrapper__whVBS&quot;]/div[@class=&quot;SearchRecruit_type_list__JemaZ&quot;]/a[@class=&quot;Anchor_element__tZBvd Anchor_white_border_gray__yLHOv&quot;]</value>
      <webElementGuid>3d7a0e12-2195-4abd-a475-a5c943c1ddbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[6]/div/div/a</value>
      <webElementGuid>344f49b3-6dd5-4453-9d75-a8f0d707011e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'# IT・通信')]</value>
      <webElementGuid>859f8c6b-5f95-42ff-a828-6973f660e993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='業種から探す'])[1]/following::a[1]</value>
      <webElementGuid>8c72d2ed-504c-47d5-8618-745af53886d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 電気・電子・機械・半導体'])[1]/following::a[1]</value>
      <webElementGuid>3e70a855-b607-4c12-a7c0-90cad5b0b306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# メーカー関連'])[1]/preceding::a[1]</value>
      <webElementGuid>ae78cea6-2d1a-4e47-876a-2ee0bf06a8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 商社関連'])[1]/preceding::a[2]</value>
      <webElementGuid>2cfd6625-4dd4-4ff2-b95a-7f5b166ec52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='# IT・通信']/parent::*</value>
      <webElementGuid>64aab574-4653-4555-9263-6530f9abfe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1')]</value>
      <webElementGuid>dfbd20b6-3bc2-45b2-b153-5dc792804230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/a</value>
      <webElementGuid>72a6e251-947e-4dd9-857b-9b322b5e8004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/industryIT%E3%83%BB%E9%80%9A%E4%BF%A1' and (text() = '# IT・通信' or . = '# IT・通信')]</value>
      <webElementGuid>b9f5ff9f-4b8d-4909-8b2a-c2bbdd07968d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
