<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>666f6e17-7869-4c17-a0a7-6e28b4d20ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Header_header__R_kkv']/div/div/h1/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;マイナビジョブサーチロゴ&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6b817811-954d-4ce2-b667-95f9822ce7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>マイナビジョブサーチロゴ</value>
      <webElementGuid>9713791a-0b30-4f24-9a2c-9d07016e6b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/servicelogo/MYNAVI_SERVICE_JOBSEARCH_YOKO_COLOR_VER2.svg 1x, /servicelogo/MYNAVI_SERVICE_JOBSEARCH_YOKO_COLOR_VER2.svg 2x</value>
      <webElementGuid>10e9414b-d46a-4a69-9c07-2d562d734fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/servicelogo/MYNAVI_SERVICE_JOBSEARCH_YOKO_COLOR_VER2.svg</value>
      <webElementGuid>67a656ca-0354-4f11-be63-9da53ba1c41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>46c63869-e3b9-4efc-8f49-db26e7966661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>4aca5e62-3dcd-4e8a-a6af-6a6c3309effc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv Header_is_root__WBV1P&quot;]/div[@class=&quot;Header_header_left__xW1Ah&quot;]/h1[1]/a[@class=&quot;Header_header_logo__T0D8R&quot;]/span[1]/img[1]</value>
      <webElementGuid>58e37f5e-13dc-463a-aea2-b71304f8b475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div/h1/a/span/img</value>
      <webElementGuid>d84da426-dbbb-4684-b42c-782560c7e8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='マイナビジョブサーチロゴ']</value>
      <webElementGuid>7d4d7709-7407-4253-a22c-e32c93f186a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>4b14185c-e464-45e5-aded-e541ee74083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'マイナビジョブサーチロゴ' and @src = '/servicelogo/MYNAVI_SERVICE_JOBSEARCH_YOKO_COLOR_VER2.svg']</value>
      <webElementGuid>0c18dc3f-1698-498e-a13c-fcd82da3da13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
