<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Hover_hover__8Ryp6_1</name>
   <tag></tag>
   <elementGuidId>1847dda9-aaff-4518-8ae5-13e0f3ace9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Header_header__R_kkv']/div/div[2]/a[3]/div/div/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c053ad50-65a0-463f-993a-d0132a45b7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icon/heart_on.svg</value>
      <webElementGuid>14c8b4ad-bccb-4068-aacc-7f35dd5baf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>51f8c231-c2ab-4a17-ac3c-db69890ff568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>edaa9019-b348-487c-a1ba-a3fbe3384971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Hover_hover__8Ryp6</value>
      <webElementGuid>b4d4a235-0e15-4abb-8553-f29071dee812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>0a25434b-b778-4716-8b6c-73c8f01603e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/static/icon/heart_on.svg 640w, /static/icon/heart_on.svg 750w, /static/icon/heart_on.svg 828w, /static/icon/heart_on.svg 1080w, /static/icon/heart_on.svg 1200w, /static/icon/heart_on.svg 1920w, /static/icon/heart_on.svg 2048w, /static/icon/heart_on.svg 3840w</value>
      <webElementGuid>5d9439cf-edcd-4544-8c23-c91461b6ef5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv Header_is_root__WBV1P&quot;]/div[@class=&quot;Header_header_links__98IMV&quot;]/a[@class=&quot;MypageMenu_icon_wrapper__DFCgn&quot;]/div[@class=&quot;Hover_element__jRytx  Hover_mypage-header-icon__pDA3q&quot;]/div[@class=&quot;Hover_img_container__gU5rQ&quot;]/span[2]/img[@class=&quot;Hover_hover__8Ryp6&quot;]</value>
      <webElementGuid>99e45a5d-62ff-4199-8469-d70f912cf56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div[2]/a[3]/div/div/span[2]/img</value>
      <webElementGuid>d505e2b2-9b84-4a09-833d-dad5679ddf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/div/span[2]/img</value>
      <webElementGuid>a60de496-0342-4e94-a5ae-286d4718de5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icon/heart_on.svg']</value>
      <webElementGuid>5de68668-a0a5-4ec3-98c8-d7163dbda476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
