<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Hover_hover__8Ryp6</name>
   <tag></tag>
   <elementGuidId>dda761dd-046d-4e03-a4ec-a011d97f4a75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Header_header__R_kkv']/div/div[2]/a/div/div/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Hover_hover__8Ryp6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f7dc459-27f4-451f-88a0-f82ac08ce8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icon/clip_on.svg</value>
      <webElementGuid>a8dcfbb4-0864-4a64-9f05-113a901581fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>518877c6-8495-4b59-8f50-7e52d6a0dbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>1a53a46c-4a58-40fe-9e65-034593792ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Hover_hover__8Ryp6</value>
      <webElementGuid>6112f12c-dbd9-4ac9-acad-be5620e908e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>f0c1c5ff-5c0e-43e5-8010-ab493251b818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/static/icon/clip_on.svg 640w, /static/icon/clip_on.svg 750w, /static/icon/clip_on.svg 828w, /static/icon/clip_on.svg 1080w, /static/icon/clip_on.svg 1200w, /static/icon/clip_on.svg 1920w, /static/icon/clip_on.svg 2048w, /static/icon/clip_on.svg 3840w</value>
      <webElementGuid>893b9e06-c823-406b-b771-76ecca61e2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv Header_is_root__WBV1P&quot;]/div[@class=&quot;Header_header_links__98IMV&quot;]/a[@class=&quot;MypageMenu_icon_wrapper__DFCgn&quot;]/div[@class=&quot;Hover_element__jRytx  Hover_mypage-header-icon__pDA3q&quot;]/div[@class=&quot;Hover_img_container__gU5rQ&quot;]/span[2]/img[@class=&quot;Hover_hover__8Ryp6&quot;]</value>
      <webElementGuid>6f33dfea-3ece-428c-a812-09e9ed84f21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div[2]/a/div/div/span[2]/img</value>
      <webElementGuid>d3afc382-74c2-486e-aa37-5239232dee98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>4ee49a8d-9fba-4962-8760-4643de51a962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icon/clip_on.svg']</value>
      <webElementGuid>0591b4a9-bf4c-4246-af61-0a85c2bc60eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
