<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sub-side-location-text</name>
   <tag></tag>
   <elementGuidId>73c52f19-7c1c-4e32-a97a-a94b2bb4811f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='sub-side-location-text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba69fa1e-c5bf-4cc8-8b9c-97bea3ef8e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5763e381-4eb1-4f2b-8e79-2ac141d808c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-side-location-text</value>
      <webElementGuid>7804b491-9637-47d5-a359-b92cff29d365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>b0f2cb5e-84dd-4ecf-bd0e-cfe47bbb7128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RefineForm_side_freeword_text__60MVP</value>
      <webElementGuid>f130f50c-a51b-4c2a-8355-3770162ed501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>都道府県、市区群、駅名など</value>
      <webElementGuid>0eaa9fdc-31ea-4d29-a49e-f9b361416a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a36c4f1b-82f9-4a2b-b571-4654f098a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>北海道</value>
      <webElementGuid>ba85cf84-0ebb-4087-8f45-08afd01e43c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]/div[@class=&quot;Search_refine_form_pc__aNEXB&quot;]/div[1]/form[@class=&quot;RefineForm_side_form__2IUw1&quot;]/div[@class=&quot;RefineForm_side_item__tcBpT&quot;]/div[@class=&quot;AccordionMenu_element__nRtPE AccordionMenu_blue-no-border__YqVad  AccordionMenu_is_open__9Vt_Q&quot;]/div[@id=&quot;list-pull-down-menu-2&quot;]/div[@class=&quot;AccordionMenu_children__7JEuS&quot;]/div[@class=&quot;undefined RefineForm_m_b_2__m1UgX&quot;]/div[@class=&quot;RefineForm_side_freeword_wrap__kbobI&quot;]/input[@id=&quot;sub-side-location-text&quot;]</value>
      <webElementGuid>8cc190bf-96bf-47c3-976a-26e483d202ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='sub-side-location-text'])[2]</value>
      <webElementGuid>8955f2b6-4c14-4e1c-ba72-2d26311b04b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='list-pull-down-menu-2']/div/div/div/input)[2]</value>
      <webElementGuid>856954ca-f3b9-4ee8-ba2a-2c6b4ef3a79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>baf94e14-50a8-4d28-a7d3-07f6a9164607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub-side-location-text' and @placeholder = '都道府県、市区群、駅名など']</value>
      <webElementGuid>77399ae7-dbb2-44ae-9af1-ad1eda01e7d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
