<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>f8e26c88-d524-4b35-911d-ff7f25f35ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3f6c8cc-d58c-4433-bfe1-cec93c77b6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8408ddd7-7378-4858-98d0-3d1902133813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>dbdb3db5-d9bc-46e2-a617-17203a8e2f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>1ec37962-318b-4491-b132-eede005f98a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>freeword_input</value>
      <webElementGuid>ae0ef55b-a3e1-4a69-b38f-38692758dbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_search_form__gPMLp&quot;]/div[@class=&quot;SearchRecruit_search_form_inner__gndQO&quot;]/form[@class=&quot;SearchRecruit_search_form_wrapper__7wtTC&quot;]/div[@class=&quot;SearchRecruit_search_form_free_word__2PXjr&quot;]/div[@class=&quot;SearchInput_base_input__Fe0O_&quot;]/div[1]/input[1]</value>
      <webElementGuid>07c9b289-ca43-4715-9086-6a284bdb2e91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>79b58f1d-c9e8-4e71-8d05-821aed0a3ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div/div/div/input</value>
      <webElementGuid>7ad982e8-fa50-431d-87a5-d9be7c0b5b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>e0bf4b1f-199b-4ba6-870c-b8709d44b68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>7f9befd6-a49e-4bd2-b235-bb3d2dcda9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
