<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sub-side-freeword-text</name>
   <tag></tag>
   <elementGuidId>ffde64ac-6e58-4b55-a7a1-031d00fa42cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7be4f757-a5b8-49ad-a791-a4558ae1e66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>723c7495-ab84-4b48-ba36-3fb5f5bf10b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-side-freeword-text</value>
      <webElementGuid>8c388cd0-4503-4b94-9db9-007faa72fe38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>7a45ef93-8ef2-43a4-a492-7973ff430c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RefineForm_side_freeword_text__60MVP</value>
      <webElementGuid>f5efb0b6-ad71-4b99-8e51-c5a7c4f2105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職種、業種、会社名など</value>
      <webElementGuid>9b4d32a5-40d1-4b03-b6fa-db4e2304a108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6cd6c822-71c4-45de-9242-5752c04a9a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>!@#</value>
      <webElementGuid>015c6ff0-702f-4455-9b6a-1af377b378d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Search_twocolumn__YUMi5&quot;]/div[@class=&quot;Search_column_side__TdR2j Search_archive_side__Bawh1&quot;]/div[@class=&quot;Search_refine_form_pc__aNEXB&quot;]/div[1]/form[@class=&quot;RefineForm_side_form__2IUw1&quot;]/div[@class=&quot;RefineForm_side_item__tcBpT&quot;]/div[@class=&quot;AccordionMenu_element__nRtPE AccordionMenu_blue-no-border__YqVad  AccordionMenu_is_open__9Vt_Q&quot;]/div[@id=&quot;list-pull-down-menu-1&quot;]/div[@class=&quot;AccordionMenu_children__7JEuS&quot;]/div[1]/div[@class=&quot;RefineForm_side_freeword_wrap__kbobI&quot;]/input[@id=&quot;sub-side-freeword-text&quot;]</value>
      <webElementGuid>7d6f7df3-d70e-49b1-84c6-bd05bf668e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='sub-side-freeword-text'])[2]</value>
      <webElementGuid>eb11cdf9-6cb1-4ee9-bc54-958f8b5f925e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='list-pull-down-menu-1']/div/div/div/input)[3]</value>
      <webElementGuid>3101d3b7-659a-42cf-9e4c-e0f5e0a7f0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>c3ee705d-9983-41ca-9c50-dd0cf84eb66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub-side-freeword-text' and @placeholder = '職種、業種、会社名など']</value>
      <webElementGuid>3e88ebba-9b0c-4d7b-961e-3986c4b449e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
