<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>d73acec4-d037-422f-9eb4-45044e324ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Header_header__R_kkv']/div/div/div/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.Header_header_logo_text__fLhol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6f028f70-c9a5-4abf-931d-d78c67fdfb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Header_header_logo_text__fLhol</value>
      <webElementGuid>4140eed8-0c93-4a68-ad08-61f5da81efa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>マイナビが提供する求人情報まとめサイト</value>
      <webElementGuid>65fa7df3-8b85-462d-8c78-7cc293bb20c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Header_header__R_kkv&quot;)/div[@class=&quot;Header_header__R_kkv&quot;]/div[@class=&quot;Header_header_left__xW1Ah&quot;]/div[1]/a[@class=&quot;Header_header_logo__T0D8R&quot;]/p[@class=&quot;Header_header_logo_text__fLhol&quot;]</value>
      <webElementGuid>be4de82b-9fd8-477b-9c2f-31a58edf0481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Header_header__R_kkv']/div/div/div/a/p</value>
      <webElementGuid>85bd1aa1-e52a-4aa3-91c4-c55f018c535d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索'])[1]/preceding::p[1]</value>
      <webElementGuid>b8b878ba-76b3-4bf5-8a99-49d68d73daae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='フリーワード'])[1]/preceding::p[9]</value>
      <webElementGuid>986f051b-50ad-4a8a-a810-2d89393a4459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='マイナビが提供する求人情報まとめサイト']/parent::*</value>
      <webElementGuid>ea9c5df4-1514-4769-8d52-58e500fcedad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>366a19b8-4433-4c91-b41f-61392c8c6dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'マイナビが提供する求人情報まとめサイト' or . = 'マイナビが提供する求人情報まとめサイト')]</value>
      <webElementGuid>24846f1d-39f7-429f-9681-c1495acfe441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
