<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_OK  20</name>
   <tag></tag>
   <elementGuidId>73c93a43-6d22-4a88-b8fd-05b55ed1bf24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.Section_element__dj6MS.SearchRecruit_feature__WRMJp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>26934d29-26c7-4cf4-acd0-7c698aa29ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Section_element__dj6MS SearchRecruit_feature__WRMJp</value>
      <webElementGuid>da5bdf60-04e8-4603-9a10-612a5dee4158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>特徴から探す# 駅近# 副業・Ｗワーク# 賞与・ボーナスあり# 高収入・高時給# 髪型自由# バイク・車通勤OK# 業種未経験者歓迎# 社会人経験20年以上歓迎# 資格を活かせる# シルバー歓迎</value>
      <webElementGuid>62befe92-0707-4f9b-8adf-496615a8ccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_feature__WRMJp&quot;]</value>
      <webElementGuid>cd11096d-c71d-4a27-b812-b3d41768b170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[7]</value>
      <webElementGuid>cc69958e-7396-4efe-aa64-26bc16dec7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 交通・物流'])[1]/following::section[1]</value>
      <webElementGuid>e6b92479-e0c8-4382-a1d4-c9470f2a2b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 不動産・建設・設備'])[1]/following::section[1]</value>
      <webElementGuid>28882c7e-a653-43b8-9db2-a6170cf8acb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]</value>
      <webElementGuid>70a70b5c-9b45-486f-b8ef-b66e7b045ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = '特徴から探す# 駅近# 副業・Ｗワーク# 賞与・ボーナスあり# 高収入・高時給# 髪型自由# バイク・車通勤OK# 業種未経験者歓迎# 社会人経験20年以上歓迎# 資格を活かせる# シルバー歓迎' or . = '特徴から探す# 駅近# 副業・Ｗワーク# 賞与・ボーナスあり# 高収入・高時給# 髪型自由# バイク・車通勤OK# 業種未経験者歓迎# 社会人経験20年以上歓迎# 資格を活かせる# シルバー歓迎')]</value>
      <webElementGuid>b85469a3-39cb-4119-b2a4-8e3ba8a1803d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
