<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_IT_1</name>
   <tag></tag>
   <elementGuidId>2d5534cd-d865-4646-ad02-769e85cdbb7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.Section_element__dj6MS.SearchRecruit_industry__Oh_KK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>6a57ce35-a543-4e8b-8c8b-2ed940bb770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Section_element__dj6MS SearchRecruit_industry__Oh_KK</value>
      <webElementGuid>1995f668-3a68-4c21-987c-971874e79a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>業種から探す# IT・通信# メーカー関連# 商社関連# サービス・レジャー# 流通・小売・フード# マスコミ・広告# 金融・保険# コンサルティング・営業# 不動産・建設・設備# 交通・物流</value>
      <webElementGuid>f9cc9091-33d2-46a3-bc54-a2819add4fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_industry__Oh_KK&quot;]</value>
      <webElementGuid>5f906af6-2ef7-444f-8bd7-4ecd9d183fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[6]</value>
      <webElementGuid>87906e9a-2010-4d27-87eb-2d91fe44f32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 電気・電子・機械・半導体'])[1]/following::section[1]</value>
      <webElementGuid>c86cf2ce-8ad3-448e-a9df-478fba644ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# 技能工・設備・配送・農林水産'])[1]/following::section[1]</value>
      <webElementGuid>050eb596-5b06-439c-a85b-45b9e037c078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]</value>
      <webElementGuid>22110688-b246-401c-b970-7290d06ce51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = '業種から探す# IT・通信# メーカー関連# 商社関連# サービス・レジャー# 流通・小売・フード# マスコミ・広告# 金融・保険# コンサルティング・営業# 不動産・建設・設備# 交通・物流' or . = '業種から探す# IT・通信# メーカー関連# 商社関連# サービス・レジャー# 流通・小売・フード# マスコミ・広告# 金融・保険# コンサルティング・営業# 不動産・建設・設備# 交通・物流')]</value>
      <webElementGuid>62e4eb3c-0690-4ff5-9a35-163f2256b9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
