<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search</name>
   <tag></tag>
   <elementGuidId>bcccffe8-3639-44b1-bb90-14463727bb06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.SearchRecruit_search_form_button__a772M</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b50a684-9878-4553-b0ee-e50b1c49e136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchRecruit_search_form_button__a772M</value>
      <webElementGuid>21b24e69-d0b7-48a3-ada6-b1f0488efe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>84d7751b-032d-49a7-8e5c-32ac3701b6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search_submit</value>
      <webElementGuid>3f08389a-e7dc-47dc-9f7c-729cf651594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ce2abe6a-b39d-4655-b23f-6981d2e8ccc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_search_form__gPMLp&quot;]/div[@class=&quot;SearchRecruit_search_form_inner__gndQO&quot;]/form[@class=&quot;SearchRecruit_search_form_wrapper__7wtTC&quot;]/div[@class=&quot;SearchRecruit_search_form_button_wrapper__dajLW&quot;]/button[@class=&quot;SearchRecruit_search_form_button__a772M&quot;]</value>
      <webElementGuid>84fc0eca-bb51-41d4-95d6-b4c05817e274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>88c6b2d5-e9aa-40bd-9ba8-8488c97a3f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[3]/button</value>
      <webElementGuid>e332c5d6-4f2e-45ea-8dfc-cfeff8f969b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=')'])[1]/following::button[2]</value>
      <webElementGuid>1b2b87aa-67a1-4a42-b8a7-39460fb031b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='( updated'])[1]/following::button[2]</value>
      <webElementGuid>eeb80314-8222-449f-9d7d-08b292cb24df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently searched terms'])[1]/preceding::button[1]</value>
      <webElementGuid>4b37221f-f7ba-442c-bd1c-1fd9eb629049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>9a4ef524-97e2-42c7-94b5-8d4345542e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'search' or . = 'search')]</value>
      <webElementGuid>b642c1b0-e147-49e2-987f-94d273d3600f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
