<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prefecture_city_station</name>
   <tag></tag>
   <elementGuidId>b473c32f-56ee-4481-8fd7-c018eaea085e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e68afa9-fd69-479b-af61-cdee52e55b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>468851ca-78ff-424c-87e0-243a84952266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>0a6afb88-9c1d-41b3-8145-2f1a5820b8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Prefectures, city groups, station names, etc.</value>
      <webElementGuid>760aa814-e50b-4259-b055-6edab829803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>area_input</value>
      <webElementGuid>4460ae01-0064-4938-b36a-450b99c85912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[@class=&quot;Section_element__dj6MS SearchRecruit_search_form__gPMLp&quot;]/div[@class=&quot;SearchRecruit_search_form_inner__gndQO&quot;]/form[@class=&quot;SearchRecruit_search_form_wrapper__7wtTC&quot;]/div[@class=&quot;SearchRecruit_search_form_free_word__2PXjr&quot;]/div[@class=&quot;SearchInput_base_input__Fe0O_&quot;]/div[1]/input[1]</value>
      <webElementGuid>93d56e20-c555-46ef-a8a6-4dc2cde1e39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>408af87a-09c5-43a4-96d3-db0695c61852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[2]/div/div/input</value>
      <webElementGuid>58db862b-420d-43c0-84fa-9ccb0bdf99f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>cc455290-93dc-4295-ad08-a5d261eae5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Prefectures, city groups, station names, etc.']</value>
      <webElementGuid>0905d1e0-797b-481c-9cf6-3808f9be6e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
