<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_link_home_page</name>
   <tag></tag>
   <elementGuidId>bc39a06a-5025-416b-b196-337d2539f863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/nav/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Breadcrumbs_breadcrumb_link__tSsxN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfab0c17-323d-4d0d-8f06-1e578f92419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Breadcrumbs_breadcrumb_link__tSsxN</value>
      <webElementGuid>cbb0d878-e1d9-400b-8d03-3300bb96689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>699d3cf0-414d-4a1a-9900-455ca43a534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ホーム</value>
      <webElementGuid>932f5fb6-f6dc-4268-b461-eea7ee732287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/nav[@class=&quot;Breadcrumbs_breadcrumb__b_9QU&quot;]/ul[@class=&quot;Breadcrumbs_breadcrumb_list__EsSA5&quot;]/li[@class=&quot;Breadcrumbs_breadcrumb_item__E2Gqt&quot;]/a[@class=&quot;Breadcrumbs_breadcrumb_link__tSsxN&quot;]</value>
      <webElementGuid>bd663feb-6450-429b-a360-d9bac36a4209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/nav/ul/li/a</value>
      <webElementGuid>b70958d1-8e80-49ee-9c97-6398df902bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ホーム')]</value>
      <webElementGuid>6f63599a-86fb-44c0-bda9-7f6ad001ade7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条件を指定してください'])[2]/following::a[1]</value>
      <webElementGuid>69faf25b-af4c-42e1-90c5-43c2f5b0d915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='解除'])[1]/following::a[1]</value>
      <webElementGuid>3633cced-a36a-4d42-b59d-9b4c50b73937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お気に入り'])[3]/preceding::a[1]</value>
      <webElementGuid>a20fa4c5-8b72-4187-9117-597e969bb281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ホーム']/parent::*</value>
      <webElementGuid>7b01fe29-77e8-4e90-a4e2-02e1a4109a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[9]</value>
      <webElementGuid>ee035e55-4380-4a9f-b410-4b52465237d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>dd02ec8f-c7ff-4a4e-9906-f5aa4fb35c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'ホーム' or . = 'ホーム')]</value>
      <webElementGuid>5900eb6d-0d93-425e-9b3b-1f49c4438128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
