<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_link_favorite</name>
   <tag></tag>
   <elementGuidId>e17ddd46-7399-4900-ad98-387396d0f9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.Breadcrumbs_breadcrumb_item__E2Gqt.Breadcrumbs_breadcrumb_active__1KYb_ > a.Breadcrumbs_breadcrumb_link__tSsxN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4676cdcf-0d78-4f38-aedf-be9211eb9a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Breadcrumbs_breadcrumb_link__tSsxN</value>
      <webElementGuid>4f1bc3d3-5257-46b1-a0db-f138cac7e215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mypage/favorite</value>
      <webElementGuid>c1d5b125-29ed-4c5e-a846-553e153a519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お気に入り</value>
      <webElementGuid>073af357-08db-43b7-8caa-8970479eeade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/nav[@class=&quot;Breadcrumbs_breadcrumb__b_9QU&quot;]/ul[@class=&quot;Breadcrumbs_breadcrumb_list__EsSA5&quot;]/li[@class=&quot;Breadcrumbs_breadcrumb_item__E2Gqt Breadcrumbs_breadcrumb_active__1KYb_&quot;]/a[@class=&quot;Breadcrumbs_breadcrumb_link__tSsxN&quot;]</value>
      <webElementGuid>314af1e8-a47a-47d2-b9ef-5028cae6019d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/nav/ul/li[2]/a</value>
      <webElementGuid>56016d8a-be15-495f-89ec-5b80067e3f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'お気に入り')]</value>
      <webElementGuid>99394063-fd3a-4965-8fe1-cbbfdb58fd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ホーム'])[1]/following::a[1]</value>
      <webElementGuid>a86e2a32-3f03-4c41-ad80-26cbaec6d133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条件を指定してください'])[2]/following::a[2]</value>
      <webElementGuid>ea627fa8-36ad-4dc8-b45b-43a7d9c2751f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/mypage/favorite')])[3]</value>
      <webElementGuid>b1acdf82-bd31-4d8d-a69f-ec05c93dad0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>945118f8-99f0-4b1a-a5f9-77fa37e96dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mypage/favorite' and (text() = 'お気に入り' or . = 'お気に入り')]</value>
      <webElementGuid>60fc1aee-b0f3-4078-9fef-3baae8b8a593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
