<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_remove_favorite</name>
   <tag></tag>
   <elementGuidId>ce81cfb9-b61a-4994-a688-2d343464e5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Mypage_alldelete__vCEXl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dfdd26c-086c-44de-b712-7e013a0be7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Mypage_alldelete__vCEXl</value>
      <webElementGuid>940c9a2e-0b59-4871-b597-b296a81371dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お気に入りをすべて解除する</value>
      <webElementGuid>b75c5d70-e37a-4bbc-9cdf-2ffad5a4fcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/section[@class=&quot;Section_element__dj6MS Mypage_content__KpXek&quot;]/div[@class=&quot;Mypage_main__m8bSq&quot;]/button[@class=&quot;Mypage_alldelete__vCEXl&quot;]</value>
      <webElementGuid>cfd3de52-4f94-4084-99f5-0be25a15c010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/div/button</value>
      <webElementGuid>ed2c4e2e-2a7b-4a77-b0e8-a3ab492b4ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提供元：'])[1]/following::button[1]</value>
      <webElementGuid>d0a8f407-9507-48f5-96d6-68ddf0487470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabcube'])[1]/following::button[1]</value>
      <webElementGuid>71f6c6dd-bc43-4c7e-82ec-07d5b7ed0ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='解除する'])[1]/preceding::button[2]</value>
      <webElementGuid>1f7e0935-dcfa-4312-aeac-634867bd4abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='戻る'])[1]/preceding::button[3]</value>
      <webElementGuid>16467bb9-d813-42b4-9e13-0b0aae3008a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='お気に入りをすべて解除する']/parent::*</value>
      <webElementGuid>1ad2b27b-10ca-4afd-b69b-a9509739e607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/button</value>
      <webElementGuid>d1edb51a-5963-43dc-95eb-d345894b8cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'お気に入りをすべて解除する' or . = 'お気に入りをすべて解除する')]</value>
      <webElementGuid>cbd894e4-37c7-4e25-a751-ca234cd66f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
